### ISSUE TITLE
#include "soci-backend.h" in sqlite3/soci-sqlite3.h

### ISSUE THREAD

**Issue by TecDroiD** [SOCI/soci#169]
Hi,

i installed soci as documented for myqsl and sqlite on a debian wheezy(amd64).
compiling a test source (that only generates a session) it sais that 

soci-backend.h can't be found in sqlte3/soci-sqlite3.h (line 27) 

which is correct, because this file isn't in sqlite3-directory but in it's parent. 
i solved this by exchanging the local include "" with a <> in soci-sqlite3.h.

you should fix this :)

**Comment by denisarnaud** [comment]
Why was that issue closed? The SOCI SQLite3 header (http://github.com/SOCI/soci/blob/master/src/backends/sqlite3/soci-sqlite3.h) still reads `#include soci-backends.h` instead of `#include <soci/backends/soci-backends.h>`.
And the same for the other back-ends. Would we like us to write a patch to fix those?

**Comment by vadz** [comment]
I'll reopen this as I apparently closed it mistakenly, but, to be honest, I am only working on the develop branch, i.e. what will become SOCI 4.x, and am not sure what is the right solution for the old version, so the most I could do here would be to apply a patch/PR.

**Comment by mloskot** [comment]
Fixed in the pull request #294 which has been already merged.
