### ISSUE TITLE
Oracle Connection to  Cluster via TNS description

### ISSUE THREAD

**Issue by wdavilaneto** [SOCI/soci#250]
Dear developers,

I've succefully developed TestCases using Oracle XE (service on other machine) and it was configured, as documentation, just like code below:

```
   sql.open(soci::oracle, "//1.2.3.4:1521/xe .." );
```

Evertything was just perfect!! Now I'm promoting the tested solution to a production server in a Oracle Cluster.  The equivalent configuration give's me the following error:

ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

I've also tryed  without success to describe TNS connection like this:

```
   sql.open(soci::oracle, "service=@(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (COMMUNITY = tcp)(PROTOCOL = TCP)(Host = $ip )(Port = 1521)))(CONNECT_DATA =(SID = $sid))) user=$usr password=$pass" );
```

This attempt gave me the following error message.

```
  ORA-12154: TNS:could not resolve the connect identifier specified
```

Does SOCI supports Oracle connection via TNS description ?

Thanks You
Walter D'Avila Neto

**Comment by miwurster** [comment]
Hey,

could someone establish a connection by specifying a TNS string?

We more or less use the following:
```
sql.open(soci::oracle, "service=@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=myhost.example.org)(PORT=5521))(CONNECT_DATA=(SERVICE_NAME=orcl.example.org))) user=sysman password=installed");
```

But we still get an error: 
```
ORA-12154: TNS:could not resolve the connect identifier specified
```

Thanks in advance for any input...
Michael

**Comment by vadz** [comment]
I don't think you can use the TNS string, you have to use `service=XE user=scott password=tiger` format.

**Comment by miwurster** [comment]
Ok, that would be fine ... but where to put the TNS string then? I assume into a `tnsnames.ora` file, right? Where do I have to put this file on the file system? Some location which is in the PATH or beside the executable, ... ?? Thanks ...

**Comment by mloskot** [comment]
Currently, SOCI does not support the Connect Descriptors as you requested in your first comment.
SOCI uses Oracle's Easy Connect Naming and SQL connect URL.

Oracle naming and connection strings are a long and fairly complex story, so it's better if you refer to the documentation where use and configuration of all the flavours are explained, see [Configuring Naming Methods](http://docs.oracle.com/cd/B19306_01/network.102/b14212/naming.htm).

Since `OCIServerAttach` does accept the **Oracle Net connect descriptors**, see [Database Connection Strings for OCI Instant Client](http://docs.oracle.com/cd/E11882_01/appdev.112/e10646/oci01int.htm#LNOCI16167), it should be possible to add support of that format to the Oracle backend. Pull requests welcome!

**Comment by wdavilaneto** [comment]
Host connection stills works for me ex:

    "service=//your_host:1521/your_sid  user=foo password=bar"

For those used to connection string with java, must pay attantion on the "/" before sid and not  ":"
