### ISSUE TITLE
Build VS2015 Win10 Errors

### ISSUE THREAD

**Issue by patodeborracha** [SOCI/soci#379]
Hi,
I Try Build SOCI in VS2015 and Win10...:
https://gist.github.com/patodeborracha/a1fa994d3b511a9ef98e#file-gistfile1-txt

What i do?

Thank You!

**Comment by vadz** [comment]
On Mon, 24 Aug 2015 05:03:41 -0700 patodeborracha <notifications@github.com> wrote:

p> I Try Build SOCI in VS2015 and Win10...:
p> https://gist.github.com/patodeborracha/a1fa994d3b511a9ef98e#file-gistfile1-txt
p> 
p> What i do?

 I thought this was fixed in 3.2 branch as well, but it definitely was in
the master, so I'd recommend getting the latest sources from git and using
them instead, especially if you're just starting with SOCI.

 Regards,
VZ

**Comment by patodeborracha** [comment]
I'll Try it..

Thank You!

**Comment by mloskot** [comment]
I haven't tried to build SOCI with VS2015 yet, so I might have missed some of the fixes in branch `release/3.2`. However, I'll be happy to apply any fixes for VS2015 to both, the master and 3.2.

**Comment by snikulov** [comment]
@patodeborracha Could you please retest on latest master? 
I suspect https://github.com/SOCI/soci/commit/bb79b6074879aaef5643521e414417fcafdd7352 should fix your problem.
