### ISSUE TITLE
...is not a member of 'sqlite_api'

### ISSUE THREAD

**Issue by spyros-rallis** [SOCI/soci#440]
Hey there! New to SOCI, and I'm trying to use it for a small db-driven (SQLite) application. But compilation fails with the following errors:

>1>c:\users\spyros rallis\documents\visual studio 2015\projects\eshop\eshop\soci\sqlite3\soci-sqlite3.h(202): error C2039: 'sqlite3_stmt': is not a member of 'sqlite_api'

>1>c:\users\spyros rallis\documents\visual studio 2015\projects\eshop\eshop\soci\sqlite3\soci-sqlite3.h(267): error C2039: 'sqlite3': is not a member of 'sqlite_api'

I'm currently using SOCI-master, but it occurs with the 3.2.3 as well. 

Here's the (minimal) code that doesn't compile:

```C++
#include <SQLite\sqlite3.h>

#include <SOCI\soci.h>
#include <SOCI\soci-backend.h>
#include <SOCI\sqlite3\soci-sqlite3.h>

#include <iostream>
#include <string>

using namespace soci;
using namespace std; 

int main(void)
{
	backend_factory const &sqlite3_factory = *soci::factory_sqlite3();

	session db(sqlite3_factory, "eshop.sqlite");

	// Irrelevant code 

	return 0;
}
```
Of course I've changed the header locations inside _soci-sqlite3.h_ to point to the correct path that sqlite3.c & sqlite3.h are found.

Any help is much appreciated.

**Comment by ArnaudD-FR** [comment]
First of all you don't have to change the header locations inside SOCI headers. But instead add some [header search path to your project](http://www.steptools.com/support/stdev_docs/help/settings_vc11.html).

If you have issues when building SOCI with SQLITE3 support, please use the following command line and update paths to match yours:
```
cd path/to/soci/sources;
mkdir build
cd build
cmake .. -DSQLITE3_INCLUDE_DIR=F:/dev/sqlite3 -DSQLITE3_LIBRARY=F:/dev/sqlite3/VisualStudio/lib/Release/sqlite3.lib
```

and do not include yourself sqlite3.h, SOCI will include it if required.

This minimun example should works:
```c++
#include <soci/soci.h>
#include <soci/sqlite3/soci-sqlite3.h>

using namespace soci;
using namespace std; 

int main(void)
{
    session db(sqlite3, "eshop.sqlite");

    return 0;
}
```

Other comments:
 * if you want to make your code portable (compilation with other compilers), don't use '\' in include paths, but use '/'
 * the following line is an error because you create a reference to a temporary object. So use soci::sqlite3 factory object.
```c++
backend_factory const &sqlite3_factory = *soci::factory_sqlite3();
```

**Comment by snikulov** [comment]
@spyros-rallis According to [current build status for MS VS 2015](https://ci.appveyor.com/project/mloskot/soci/branch/master/job/v2eoma2a3npl0wgk) all sqlite tests are passed.

Could you please send your questions to soci-users@lists.sourceforge.net mail list first?

```
 The following tests passed:
	soci_empty_test
	soci_empty_test_static
	soci_mysql_test
	soci_odbc_test_mysql
	soci_odbc_test_mysql_static
	soci_postgresql_test
	soci_postgresql_test_static
	soci_sqlite3_test
	soci_sqlite3_test_static
```
