### ISSUE TITLE
Coverity not fully configured

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#472]
I'm not sure why, but coverity displays "Not fully configured" message.

![soci-coverity](https://cloud.githubusercontent.com/assets/80741/15276817/b2373594-1aea-11e6-9bca-3fb20bbed58a.png)

**Comment by snikulov** [comment]
@mloskot It's because project also should provide 'modeling file'.
I don't have much time to investigate what should it be, so maybe later :)

It's not error, just to help analyzer understand code properly.

![untitled](https://cloud.githubusercontent.com/assets/142123/15283625/b41cd2e6-1b54-11e6-95fe-ee383c6e33c5.png)

**Comment by vadz** [comment]
I don't think we need one for SOCI, the only use for this modelling file I know is to mark "fatal abort" function as never returning, but we don't have any such functions in SOCI.

Maybe you can create an empty modelling file just to get rid of the (annoying, I agree) warning...

**Comment by snikulov** [comment]
@vadz @mloskot I've created an empty model file and add it into the configuration. Now all clear.

**Comment by mloskot** [comment]
Nice, thanks!
