### ISSUE TITLE
Blob offset not uniform between backends

### ISSUE THREAD

**Issue by msobczak** [SOCI/soci#499]
Hi,
The read/write operations for BLOB objects expect the "offset" parameter, which is not handled uniformly across backends.
In particular, Oracle expects 1 to denote the first byte of the BLOB object, wherease PostgreSQL expects 0 as the beginning index. This is reflected in the existing unit test cases.
This makes it more difficult to write backend-agnostic applications.

Is this considered to be a problem?

**Comment by mloskot** [comment]
Although I don't recall any issues reported, unification would be nice, I guess.

**Comment by msobczak** [comment]
The big question here is whether the unconditional unification (that is, changing the current behaviour for one of the databases) would break any existing application.
It might be possible to introduce a configuration parameter (in a connection string, perhaps) with the intended starting index for those applications that care to have it unified. The lack of this additional parameter would preserve the existing behaviour, which would protect existing code that relies on one or the other index value.

**Comment by mloskot** [comment]
AFAICT, those involved, developers and users, have accepted SOCI 4 may break compatibility in many places. That is one of the reasons SOCI 4 (current `master`) has been running for long time now without packaged release.

**Comment by vadz** [comment]
API breakage is one thing and acceptable in a major release. Silent breakage like this is another matter entirely and I'm less sure about it.

**Comment by mloskot** [comment]
@vadz I consider parameters of public API functions are part of the API. I also consider a parameter domain (e.g. valid values `0` or `1`) part of the API. Hence, I wouldn't call such change a silent breakage (I also assume it would be documented).

**Comment by vadz** [comment]
@mloskot Sorry, I should have made it clear that I use "silent breakage" in its usual, well-defined, meaning of "change in behaviour not resulting in any compilation error or warnings". And this would be exactly this, which is rightly considered to be the worst possible kind of incompatibility: it's much better to prevent the code from compiling, than to let it compile, but do the wrong thing silently.

Because of this, unless we have a very good reason to believe that this API is not used at all, my ideal choice would be to add some new consistent API and deprecate the existing one. If this is considered too drastic/time-consuming, then I prefer @msobczak's proposal of keeping the current behaviour by default and adding an option. This is, IMHO, less elegant than a new API but simpler to implement.

But personally I'd always do just about anything else rather than silently change an API behaviour. I realize that this is not a universally shared point of view and SOCI may use a different approach, of course.

**Comment by mloskot** [comment]
@vadz 
> "change in behaviour not resulting in any compilation error or warnings"

I see what you mean. You've got the point.

I have no preference, any solution will work for me.

**Comment by msobczak** [comment]
What about adding new functions like read_from_start(), which would guarantee offsets counted from 0? The old functions read/write would have to be clearly documented that they interpret their parameters in a backend-specific way. This way existing programs would not be affected and new programs could benefit from the unified API.

**Comment by vadz** [comment]
This (`read_from_start()`) is very close to my ideal solution, but I wonder if we couldn't avoid introducing a new function name and just add an overload, e.g. `read(char * buf, std::size_t toRead, std::size_t offset = 0)`? I think it should be unambiguous (for the compiler, I realize this could be confusing for the human beings) because in an existing `read(0, buf, len)` call, `0` could be interpreted as a pointer, but `buf` can't be implicitly converted to `size_t`.

Then we could deprecate the existing version and, maybe, remove it in SOCI v5.

**Comment by msobczak** [comment]
Two overloaded functions with the same types of arguments but different order is a very bad idea. Especially when two arguments have the same type already.
It would be probably better to introduce the function that you mentioned and *remove* the old one and thus force all existing users (that is, "all three of them") to adapt their code. Then - no need to deprecate anything. If this is considered too aggressive, introduce another function with clearly distinct name.

**Comment by mloskot** [comment]
Fixed in #508
