### ISSUE TITLE
use vector for `in`

### ISSUE THREAD

**Issue by redboltz** [SOCI/soci#520]
I'd like to use `std::vector<std::string>` for the list of `in()`.

For example, in the following SQL, I'd like to give multiple parameters for `in()`. They are dynamically decided.

```sql
select count(*) from  MYTABLE where NAME not in ('NAME1', 'NAME2', ...)
```

I wrote the following code:

```cpp
std::vector<std::string> names;
names.emplace_back(...);
int count = 0;
sql << "select count(*) from  MYTABLE where NAME not in (:names)", use(names), into(count);
```

It seems that `in()` does not support bulk operation.
Am I missing something?

I can do that manually. I mean concatenating the query string something like `:name,` and then, use `statement` and `exchange(use(names[i]))`. But before I do that, I'd like to know more elegant way if it exists.

**Comment by mloskot** [comment]
The operand of SQL `IN` operator expects SQL list of values or string (depending on DBMS). That is, the operand is an SQL value, not C/C++/or other API specific value.
Having said that, AFAIK, binding external list to `IN` is not possible.

Do you know any database client API that allows such think?

**Comment by redboltz** [comment]
@mloskot , thank you for the quick response. I'm not sure I understand 100% correctly what you mean. But I understand my requirement depends on Database APIs. I didn't understand that what kind of process is done by soci, and DB API, but now I understand.

I think that if I want to do bulk notation using `:names`, the DB API needs to proved the following two functionalities.

 1. Permit placing maker to in() clause.
 2. If 1 is satisfied, the marker can be corresponding to the list of values.

I'm using MySQL. And checked the document.
https://dev.mysql.com/doc/refman/5.6/en/mysql-stmt-prepare.html

I understand that I can't place a marker to `in()` clause. (1 is not satisfied.)
So, I will build my query using string operations in C++.

**Comment by sinall** [comment]
It is likely we need a sql builder for this.

**Comment by pestophagous** [comment]
The situation is more complicated than just saying either:
- "this works in SOCI", or 
- "this does not work in SOCI"

In fact, when placing a SOCI bind marker inside `IN` and supplying a vector, it "_partially works_" and "_partially silently fails_", which could be seen as a less desirable behavior than "it does not work at all."  I will give several examples below.

I'm grateful that this GitHub issue exists, because it helped me confirm what I was observing.

I think this is a case where SOCI's admirably high usability and intuitive API are (in a sense) "making it irresistible" for users to fall into this trap of thinking a `vector` can be supplied for populating a SQL `IN` clause.

-----------------------------------
### My Environment

I am building SOCI `4.0.0` from source on Ubuntu 18, using the following commit:

```
3742c894  2019-11-09  Mateusz Łoskot   (HEAD, tag: 4.0.0, origin/release/4.0) Merge branch 'master' into release/4.0
```

My DBMS is MariaDB 10.

-----------------------------------


In my case, prior to today, I would have sworn to you that it is possible to put a SOCI binding marking in an `IN` clause and supply a `vector` for populating it.

I would have sworn it, and indeed it is possible!

Some code that I have relied on for several months looks like this:

```
-- the query

        DELETE FROM MyTable
        WHERE my_id IN (:MY_IDS);

// the cpp code

    const std::vector<int> idvector;
    // populate the vector ....

    soci::statement del = ( sql.prepare << GetQueryString(),
                soci::use( idvector ) );
    del.execute( true );
```

In the above code, things behave according to my intuition.

What I did not investigate until today (using the Mariadb General Query Log) is that for the above code, `SOCI` generates multiple `SQL` statements, as in:

```
DELETE FROM MyTable         WHERE  my_id IN (0)
DELETE FROM MyTable         WHERE  my_id IN (1)
DELETE FROM MyTable         WHERE  my_id IN (2)

```

Because I have been observing with great confidence for several months that the above code is performing as I wish, this led me to conclude that "yes, putting a bind marking inside the `IN` and supplying a `vector` is supported."

This led me to the case where it *partially* works.

Today I wrote new code like the following:

```
-- SQL query

        SELECT
          p.product_id
        , c.display_name
        , c.sort_number
        FROM Product p
        JOIN ProductCertificationJoin pcj
         ON p.product_id = pcj.product_id
        JOIN Certification c
         ON pcj.certification_id = c.certification_id
        WHERE p.product_id IN (:PROD_IDS);

// cpp code

        const std::vector<int> idvector;
        // populate the vector ....

        soci::rowset<soci::row> rs = ( sql.prepare << GetQueryString(),
                soci::use( idvector ) );

        for( soci::rowset<soci::row>::const_iterator it = rs.begin(); it != rs.end(); ++it )
        {
              // operate on results
        }
```

What the `SOCI` mysql backend actually did was to take the FIRST ITEM in the `vector` (aka `idvector[0]`) and substitute just that single `int` to produce a where clause such as:

```
WHERE p.product_id IN (16)
```

The vector actually contained `{16,26,26,18,24,15,19,11,21,28}`, so:

```
WHERE p.product_id IN (16) --  what actually happened.

WHERE p.product_id IN (16,26,26,18,24,15,19,11,21,28)  -- what i expected to happen
```

That is what I call "partial success", and I would prefer to get "total failure" (log an error or throw an exception or both) instead of "partial success". The partial success masked the issue for a little while.

Like @redboltz, I have created a perfectly acceptable workaround using C++ string operations (specifically `std::regex_replace`). Therefore, I am not seeking any urgent fix.

As `SOCI` gains a larger and larger user base (which I expect it will, because it is an excellent library), I suspect more people will run into this subtle issue, so I felt that adding detail to this discussion would be helpful.

**Comment by hrabe** [comment]
Even if I agree with supporting in statements you should consider, then in clauses not provided by a subselect are limited by databases different. It would be rejected, if you pass 1000 values to oracle as example.

**Comment by pestophagous** [comment]
> Even if I agree with supporting in statements you should consider, then in clauses not provided by a subselect are limited by databases different. It would be rejected, if you pass 1000 values to oracle as example.

Great point.

When Oracle does such a rejection, I would hope that some error is sent back and is detectable by the SOCI-Oracle backend. If that is the case, and if SOCI propagates (or at least logs) that error, then I would still treat these as two distinct questions:

1. Should SOCI itself allow a `vector` to bind to an `IN`?
2. Should the underlying DBMS support various forms of `IN` (with/without bindings, with/without length limits)?

Clearly, SOCI only has control over the first question.

It sounds like (for the most part) SOCI already wants to answer "no, we do not allow a vector to bind to an `IN`". That choice seems very well justified.  So to aid in future enhancement, I posted my "partially working" case so that SOCI contributors (maybe even myself, time permitting) could "enhance the choice of non-support" by throwing an exception in the case that currently partially works.

SOCI is a phenomenally elegant C++ library that also respects the beauty of SQL. Thanks again to the whole team.
