### ISSUE TITLE
Split AppVeyor jobs per backend

### ISSUE THREAD

**Issue by mloskot** [SOCI/soci#550]
Pros:
* Better view on tests passing per backend
* Easy way to allow failures for some 'mysterious' issues (see @vadz proposal in https://github.com/SOCI/soci/pull/548#issuecomment-316215044)

Cons:
* More complex appveyor.yml setup
* Potentially longer build times

**Comment by vadz** [comment]
MySQL problem can be seen in Travis when running with address sanitizer too, there seems to be a real bug here, so disabling it doesn't look like a good after all...

**Comment by mloskot** [comment]
Understood.  Let's keep this open for now though

**Comment by mloskot** [comment]
@vadz What's your comment on splitting, for, against, neutral? Do you see more serious disadvantages?

**Comment by vadz** [comment]
To be honest, I think it's a bad idea because AppVeyor seems to take quite a long time to launch new builds, so increasing their number risks making the time taken by its check even longer than now, and it's already uncomfortably slow right now, as I could see yesterday (I had several not quite independent PRs and it took several hours for the builds to go through, even though I manually cancelled quite a few of them to speed things up).

**Comment by mloskot** [comment]
Yes, AppVeyor (free tier) is not speed killer.
