### ISSUE TITLE
Is there anyway to checking the databae connection is open or not?

### ISSUE THREAD

**Issue by mayankahm** [SOCI/soci#669]
@mloskot 
Hi, I have come in situation where i need to check that, MySQL database connection is open or not?
could you help me is there anything in api where i can get bool to represent database connection.

**Comment by vadz** [comment]
There is no such method currently and you basically have to "ping" the database by trying to execute some idempotent operation (e.g. `select 1`) and check if it fails or not.

I'm closing this because #504 discusses basically the same thing and, generally speaking, the issue tracker is not the best place for asking questions (we have the mailing list and the chat channel for this).
