### ISSUE TITLE
Generate VS Solution using /MT rather than /MD

### ISSUE THREAD

**Issue by alastairUK** [SOCI/soci#698]
I am using:

cmake.exe -G "Visual Studio 15 2017" -DWITH_BOOST=OFF -DWITH_FIREBIRD=OFF -DWITH_ORACLE=OFF -DWITH_DB2=OFF -DWITH_MYSQL=OFF -DWITH_POSTGRESQL=OFF -DWITH_SQLITE3=OFF -DCMAKE_INSTALL_PREFIX="C:\Soci\install" -DSOCI_TESTS=OFF -DSOCI_CXX_C11=ON -DSOCI_EMPTY=OFF -DSOCI_SHARED=OFF -DCMAKE_CONFIGURATION_TYPES:STRING=Release;Debug

To generate soci_core_static/soci_odbc_static

But I note that the projects use /MD (Multi-threaded DLL) rather than /MT. 

I tend to think of static being all static (i.e not using any runtime DLLs)

Is there a configuration option to set it to use /MT?

**Comment by mloskot** [comment]
> I tend to think of static being all static (i.e not using any runtime DLLs)

That is a matter of personal/project preference.

Let's consider the Boost.Build speak, which in my opinion makes the distinction vividly clear - `b2` commands accepts `link=static|shared` and `runtime-link=static|shared` - any combination of the values is valid.

Unfortunately, CMake does not offer equivalent of `b2`-s `runtime-link` and the 'canonical' way to request `/MT` instead of the default `/MD` is [fiddling with `CMAKE_CXX_FLAGS`](https://cpplang.slack.com/archives/C5Y2GDECX/p1545049161547900):

First, clear the defaults:

```
string(REGEX REPLACE "/MD" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
string(REGEX REPLACE "-MT" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
```

Then,

```
target_compile_options(soci_core_static $<$<CXX_COMPILER_ID:MSVC>:-MT> ...)
```

Currently, you would have to patch `CMakeList.txt`-s on your own, locally.

Our CMake configuration could offer `SOCI_RUNTIME_LINK_STATIC=ON|OFF` as sort of equivalent option to `b2`-s `runtime-link`.

I am working on complete rewrite of the CMake configuration for SOCI 4, see https://github.com/mloskot/soci/tree/ml/modern-cmake, so I will consider adding such option. Let's keep this open.

**Comment by alastairUK** [comment]
Thanks for the reply!

I agree being able to specify the link and runtime settings like b2 would be incredibly useful. 

I will attempt to modify my local CMakeList.txt to do what you suggest.

**Comment by myd7349** [comment]
https://github.com/protocolbuffers/protobuf/blob/master/cmake/CMakeLists.txt#L139-L153

**Comment by mloskot** [comment]
If anyone wants to improve the CMake configuration to allow `/MT`, feel free to propose a PR.
