### ISSUE TITLE
std::tm timestamp problem with DST

### ISSUE THREAD

**Issue by Saring** [SOCI/soci#723]
In timezone with the 'daylight savings time' (e.g. Europe/Prague), it's not possible to read 31.3. 2:00:00 from database (e.g. postgresql: timestamp without timezone), because mktime() will always change it to 3:00:00

```c++
TEST_CASE("Time DST", "[postgresql][dst-time]") {
	// hack: set Europe/Prague time zone
	setenv("TZ", "Europe/Prague", 1);

	soci::session sql(backEnd, connectString);

	sql << "drop table if exists soci_test;";
	sql << "create table soci_test(id integer, ts timestamp)";

	// winter summer time shifts from 2:00 -> 3:00
	// but we use the database for UTC values
	sql << "insert into soci_test values (1,'2019-03-31 02:00:00'),(2,'2019-03-31 03:00:00')";

	std::tm t1 {};
	std::tm t2 {};

	sql << "select ts from soci_test where id=1", into(t1);
	sql << "select ts from soci_test where id=2", into(t2);

	// it is not possible to determine if original DB value was 2:00 or 3:00
	// because t1 == t2
	bool t1_equals_t2 = 
		t1.tm_mday == t2.tm_mday &&
		t1.tm_mon == t2.tm_mon &&
		t1.tm_year == t2.tm_year &&
		t1.tm_hour == t2.tm_hour &&
		t1.tm_min == t2.tm_min &&
		t1.tm_sec == t2.tm_sec &&
		t1.tm_isdst == t2.tm_isdst &&
		t1.tm_gmtoff == t2.tm_gmtoff;

	// fails
	CHECK_FALSE(t1_equals_t2);
}
```

So do I have to change time zone of whole program, to be able to read '2019-03-31 02:00:00' from the database?

**Comment by mloskot** [comment]
The string with timestamp is parsed here

https://github.com/SOCI/soci/blob/95e4633a5f00b2f75cd7d79a5266476181bc316d/src/backends/postgresql/standard-into-type.cpp#L108-L111

Possibly, the parser needs to be improved

https://github.com/SOCI/soci/blob/56bc9f9c5e1f12c43217f4949cf70489d91ed4c9/src/core/common.cpp#L45-L93

PRs welcome!

**Comment by Saring** [comment]
I dont think it Postgresql only problem.
`soci::details::parse_std_tm` parses 31.3.2019 2:00:00 with `is_dst=-1` and `tm_gmtoff=0`

But then `mktime_from_ymdhms` is called:

```c++
inline
void
mktime_from_ymdhms(tm& t,
                   int year, int month, int day,
                   int hour, int minute, int second)
{
    t.tm_isdst = -1;
    t.tm_year = year - 1900;
    t.tm_mon  = month - 1;
    t.tm_mday = day;
    t.tm_hour = hour;
    t.tm_min  = minute;
    t.tm_sec  = second;

    mktime(&t);
}
```

and `mktime` changes it from 2:00:00 to 3:00:00

It is just not possible to store 31.3.2019 2:00:00 in the `std::tm`, when it does not exist in current time zone. Because time skips from 1:59 to 3:00 then anything between 31.3. 2:00 and 31.3. 2:59 cannot be returned as `std::tm` after the `mktime` call.

Any plans for replacing `std::tm` with another data type?

**Comment by rosscsoft** [comment]
I have analysed this issue in relation to my team's project and it potentially affects every SOCI user (regardless of database) running on a system with Daylight Saving Time enabled (most people I'd guess). There are specific hours that will not be read correctly from the database and will be inaccurate by 1 hour.

Writing to the database via soci::use() is affected also. If a std::tm with a specific date/time is passed to soci::use(), the library will (quite unexpectedly!) change the value of the input variable by 1 hour. However, the original value will be written correctly to the database. If the input variable is const, an "Attempted modification of const use element" error will occur. 

Our application uses SOCI with Oracle on a standard UK timezone (with DST) on Windows 10 and I experience this problem. It affects PostgreSQL also but is not a PostgreSQL-specific issue so could we lose the PostgreSQL label?

As Saring pointed out, this is due to mktime() altering the input std::tm time as part of its normalisation function.  In UK timezone with DST enabled, an input date/time that falls within the hour where clocks go forward (e.g. 31 March 2019 01:00) will be moved forwards or backwards 1 hour depending on the value of tm_isdst.  Presumably this is because mktime() expects to operate on local time and in UK+DST the aforementioned time does not exist.  However, in our application date/times are UTC where it would be legitmate.

You can write a test app to examine mktime() behaviour for your timezone by looping through every hour of the year, calling mktime() and checking whether mktime has modified the input. Changing tm_isdst affects whether the input time is moved forwards or backwards but there is no value that prevents modification in my timezone.

The reason this issue affects SOCI is because mktime() is used in mktime_from_ymdhms() to normalise a std::tm that has been read from database client libs.  When reading a date/time from the database, a std::tm is created from the internal db format and mktime() is used to normalise that value.  When writing to the database, after the write has been performed, the input value (in internal db format) is read back again (to allow for in/out parameters) and converted to std::tm which is validated by mktime().  Interestingly, mktime() normalisation is not applied to the value before it is written to the database.

My thoughts are that any std::tm passing through the SOCI API should be written to/read from the database verbatim with no localisation. To my knowledge, SOCI does not handle database types that include timezone information and therefore all times are naive/unaware of timezone. SOCI would need a different type to hold a timezone-aware date/time since members tm_zone/tm_gmtoff are unsupported on many platforms (e.g. Windows).

POTENTIAL SOCI SOLUTIONS

1) In mktime_from_ymdhms(), replace the call to mktime() with a call to _mkgmtime() on Windows or timegm() on Linux/BSD. This works like mktime() but always assumes GMT/UTC so does not adjust times for local timezone. We have implemented this temporarily in our local build and it works OK.

Unfortunately these are not standard C/C++ functions. SOCI could define timegm() as _mkgmtime() on Windows builds but are there other platforms for which this might be a problem?

2) Remove the mktime() call from mktime_from_ymdhms() altogether. Just poke the parameters into the std::tm and return it with tm_isdst=0 (or perhaps -1), tm_wday=-1, tm_yday=-1.  

I question whether normalising via a call to mktime() is necessary. Historically, std::tm has often been considered to represent local time but there have always been exceptions to this.  It seems to me that SOCI API is just using std::tm as a convenient DTO for y,m,d,h,m,s since tm_isdst, tm_wday, tm_yday are ignored when converting to internal db formats. If it is just a DTO with no implied localisation semantics, does it need normalising?  

Currently, mktime() normalisation is only applied to values being read back from database client libs.  Is it likely that the database would produce an output that requires normalisation? Is it necessary to calculate tm_wday, tm_yday? If so, perhaps it should be the responsibility of the client application to call mktime()/_mkgmtime()/timegm() as they see fit?  Given that the database time value is zoneless I don't think we should assume it bears any relation to the client machine timezone so should avoid making calls that bring localisation into play.

3) Implement one of the above choices with a build option that allows the SOCI user to choose if they wish to preserve the current behaviour or adopt one of the above.

**Comment by rosscsoft** [comment]
Any thoughts on this?  I'm happy to implement a fix but could use a steer on the desired approach

**Comment by vadz** [comment]
Thanks for looking at this! It's clearly a bad bug and I just didn't have the courage to dive into it as I know that everything DST-related _always_ takes more time than foreseen.

Ideal, I think, would be to have some SOCI-specific type representing the time(stamp) with TZ info, but this is probably going to require a lot of work, so I agree that just passing the contents of `struct tm` transparently to/from the database is the best we can realistically do right now.

If we can just do (2), I don't see any reason to do anything else. I think we can trust database libraries to return valid dates (unless somebody knows of an example disproving this) and we can make having a valid date a precondition in the other direction. If we find some example showing that we really need to call `timegm()` (which is more or less universally available IME), we could do (1), but (2) seems preferable. Finally, I strongly dislike (3) because I don't see any reason why we should burden SOCI users with having to make any choices there -- this should just work correctly.

One last thing: we really need to have a (currently failing) test checking for this, to ensure that not only this (difficult to notice in normal use) bug is fixed, but that it remains fixed in the future.

Thanks again for looking at this!

**Comment by rosscsoft** [comment]
Great, thanks - yes, the analysis has been fairly time-consuming but I think I have a decent handle on the issues now.

I'll have a look at doing (2) + test.

**Comment by rosscsoft** [comment]
Was hoping to have got to this by now but have been diverted by other tasks.  This is still on my TODO list and hopefully I'll fit it in next week.
