### ISSUE TITLE
Postgresql - how to connect with 'port' and 'host' options?

### ISSUE THREAD

**Issue by vaibhavM55** [SOCI/soci#734]
I have 2 versions of postgresql installed in my system (9.5 and 11). I want to use the postgresql 11 with soci. So inorder to do that, I have to provide the 'host' (127.0.0.1) and 'port' (5433) options along with the 'dbname', 'user' and 'password' options. But I am unable to connect to the postgreql 11. There is no issue with my postgresql cos I use it with django and pass the same parametes and values to the connection. I have tried all the following things but to no success.

```
//session sql("postgresql", "dbname=sociTest1 user=vaibhav password=vaibhav");
		//session sql("postgresql", "dbname=sociTest1 user=vaibhav password=vaibhav port=5433");
		//session sql(postgresql, "dbname=sociTest1 user=vaibhav password=vaibhav port=5433");
		//session sql("postgresql://dbname=sociTest1");
		session sql("postgresql", "pghost=localhost user=vaibhav password=vaibhav dbname=sociTest1 pgport=5433");


(1) ->	//connection_parameters parameters("postgresql", "dbname=sociTest1");
(2)->	//connection_parameters parameters("postgresql", "dbname=sociTest1 user=vaibhav password=vaibhav");
		//parameters.set_option("user", "vaibhav");
		//parameters.set_option("password", "vaibhav");
		//parameters.set_option("host", "127.0.0.1");
		//parameters.set_option("port", "5433");
		//session sql(parameters);
```
I have tried all the combinations of the commented out options. But all I get is either an abort() pop up, or if I don't pass the 'host' and 'port' options in the 'session sql()' constructor - I get password error (as expected), or using the 'parameters.set_option()' - It gives a password not provided error (even though I did provide it). I even tried the combinations of providing the 'password' option in the connection_parametes() constructor and then passing only the 'host' and 'port' in the parameters.set() method ( see marked (1) and (2) ), but to no avail. Pls help.

**Comment by tt4g** [comment]
The connection parameter of SOCI specifies that of libpq, have you tried specifying `host` parameter in session constructor?

As far as I know, there is only one parameter that specifies the connection destination,
See PostgreSQL documentation.

> https://www.postgresql.org/docs/11/libpq-connect.html

Here's the code snippet I used to connect:

```cpp
#include <soci/soci.h>
#include <soci/postgresql/soci-postgresql.h>

int main() {
    soci::session sql(*soci::factory_postgresql(),
                      "user='soci_user' password='soci_pass'"
                      " host='127.0.0.1' port=5432 dbname='soci_test'"
                      " application_name='soci_test_app' connect_timeout=10"
                      " options='-c client_encoding=utf8'");

    // use session ...

    return 0;
}
```

**Comment by tt4g** [comment]
I checked it because I did not know `soci::connection_parameters`, but it seems that the parameters passed to the constructor are wrong.

You need to set all connection parameter for `connectString` of `connection_parameters::connection_parameters(std::string const & backendName, std::string const & connectString)`.

The option set by `connection_parameters::set_option(const char * name, std :: string const & value)` is not used for connection.

Although details are omitted, generation of `connection_parameters` and connection generation by PostgreSQL factory are performed by the following link destination code.

Although details are omitted, construct of `connection_parameters` and connect by PostgreSQL factory are performed by the following link destination code:

https://github.com/SOCI/soci/blob/3a1f602b3021b925d38828e3ff95f9e7f8887ff7/src/core/connection-parameters.cpp#L47-L51

https://github.com/SOCI/soci/blob/3a1f602b3021b925d38828e3ff95f9e7f8887ff7/src/backends/postgresql/session.cpp#L44-L72

I think that the cause of `abort ()` is also `postgresql_session_backend::connect` because `soci::error` is thrown when it can not connect.

**Comment by tt4g** [comment]
Your code may work as follows:

```cpp
connection_parameters parameters("postgresql", 
        "dbname=sociTest1 user=vaibhav password=vaibhav host=127.0.0.1 port=5433");
session sql(parameters);
```
