### ISSUE TITLE
Finding instantclient and using cmake_policy 

### ISSUE THREAD

**Issue by abrownsword** [SOCI/soci#737]
I am trying to use SOCI with Oracle InstantClient, and am having difficulty getting it to locate my library directory.  I am invoking SOCI's cmake from my own cmake build using add_subdirectory.  Prior to invoking it I am setting the various variables documented to be used:

set(SOCI_CXX_C11 on)
set(SOCI_SHARED off)
set(SOCI_STATIC on)
set(SOCI_TESTS off)
set(WITH_BOOST on)
set(BOOST_ROOT "$ENV{DEPS_ROOT}/boost/distro")
set(WITH_DB2 off)
set(WITH_FIREBIRD off)
set(WITH_MYSQL off)
set(WITH_ODBC off)
set(WITH_ORACLE on)
set(ORACLE_INCLUDE_DIR $ENV{DEPS_ROOT}/instantclient/distro/include/)
set(ORACLE_LIBRARIES ${CMAKE_CURRENT_SOURCE_DIR}/../instantclient/distro/lib/)
set(ORACLE_HOME ${CMAKE_CURRENT_SOURCE_DIR}/../instantclient/distro/lib)
set(WITH_POSTGRESQL off)
set(WITH_SQLITE3 off)

I am also setting the cmake policies to get rid of the warnings, however I still get the one for CMP0048:

cmake_policy(PUSH)
cmake_policy(SET CMP0048 NEW)
cmake_policy(SET CMP0077 NEW)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/distro)
cmake_policy(POP)

Any suggestions?  And any timeline for an official 4.0.0 release?

(addendum:  should also mention I'm using the latest lite InstantClient library)

**Comment by tt4g** [comment]
Maybe related: #702 

The path specified for `ORACLE_LIBRARIES` will probably not be used.
If you look at `FindOracle.cmake` in SOCI 3.1.0, you should set these variables because `ORACLE_OCI_LIBRARY`, `ORACLE_OCCI_LIBRARY` and `ORACLE_NNZ_LIBRARY` are specified as variable names in `find_library`:

https://github.com/SOCI/soci/blob/0ecdbfa6e4578a8fc6fa1e07b282f8496dd6ccc5/src/cmake/modules/FindOracle.cmake#L46-L48

Specify the above variables in CMake.
Also, the library path must be completely specified up to the library file (e.g. `/usr/local/instantclient/distro/lib/libclntsh.so`).

Furthermore, you seem to need to specify the `ORACLE_HOME` environment variable,
In CMake, it is specified by `set(ENV{ORACLE_HOME} ...)`:

https://github.com/SOCI/soci/blob/0ecdbfa6e4578a8fc6fa1e07b282f8496dd6ccc5/src/cmake/modules/FindOracle.cmake#L26-L28

**Comment by abrownsword** [comment]
Seems I have it building now.  I had to hack the FindOracle to add the xxxx18 variations.  Who knows if it’s going to run, or even continue to compile as I start trying to use SOCI.

**Comment by mloskot** [comment]
I have not tried SOCI with latest Oracle Instant Client, so the CMake configuration may need updating.

I have a tentative plan to submit `FindOracle.cmake` or similar to CMake upstream, but it's not ready yet.

> Any suggestions? And any timeline for an official 4.0.0 release?

https://github.com/SOCI/soci/issues/616#issuecomment-501593561

**Comment by abrownsword** [comment]
I also had to hack the FindOracle.cmake to use the variables I set rather than overwriting them with an unsuccessful find attempt.  Didn't really dig deeper into why the *second* find was failing as I just want to tell it where to look directly (these cmake find operations are always so fraught with problems).

**Comment by mloskot** [comment]
CMake Find-mobules are just _guessers_ w/o much magic powers.
Oracle does not ship Config-modules unfortunately.

I will try to remember to take your notes into account when I'll get back to the `FindOracle.cmake` thing.
