### ISSUE TITLE
PostgreSQL failover connection string

### ISSUE THREAD

**Issue by Glandos** [SOCI/soci#793]
It seems that the connection string is not parsed the same way as `session.open`.
I use exactely the same string in `open` and as `newTarget` parameter in the `failed` callback, and I have the following error:
```
could not translate host name "dbname=post_db" to address
```
Connection string is `"postgresql://dbname=post_db"`.

As I see it, the failover call [`set_connection_string`](https://github.com/SOCI/soci/blob/release/4.0/src/backends/postgresql/error.cpp#L119) and `open` use the constructor of `connection_paramaters` that also call [`parseConnectString`](https://github.com/SOCI/soci/blob/release/4.0/src/core/connection-parameters.cpp#L58). I didn't have time to dig it further.

I also expected that the failover algorithm would reuse the same connection string if `newTarget` is missing.

**Comment by vadz** [comment]
I agree that it's a problem and I've fixed it locally, but beyond this I don't understand how is failover supposed to work at all for PostgreSQL -- or, rather, I'm pretty sure that it doesn't work and is fundamentally broken because it was apparently added without any testing whatsoever :-(

The problem is that even if reconnecting works, an exception is still thrown -- and in any case the original operation is not retried. Maybe I'm missing something here, but I just don't see any point in using this failover mechanism at all.
