### ISSUE TITLE
SOCI not found for libsoci_core.so.4.0 in libsoci_mysql.so by linux tool ldd

### ISSUE THREAD

**Issue by szstonelee** [SOCI/soci#811]
Thank the SOCI team for SOCI make my project Redisoo (github.com/szstonelee/redisoo)work. SOCI is a great project!

When I use the soci library, I found an issue with libsoci_mysql.so which was described as 'not found' with libsoci_core.so.4.0 by linux tool ldd. It can let the application output the error message of "Failed to find shared library for backend mysql". 

You can check the detail of issue here at https://github.com/szstonelee/redisoo/blob/master/build.md

I searched the Internet and found someone said they had the same issue. 

I fixed the problem by export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64 and rebuild the soci library. You can check the detail in the same git hub page.

Maybe it is related to the build dependency of shared library. The following link has some info about this. https://stackoverflow.com/questions/11055569/linking-with-dynamic-library-with-dependencies. I just doubt and am not sure.

BTW, Mac OS does not have this problem. It just happened in Linux.

**Comment by vadz** [comment]
Sorry, I don't understand what the problem is here. If you don't install SOCI shared libraries in one of the standard locations searched by ld (see `/etc/ld.so.conf`), you need to set `LD_LIBRARY_PATH` accordingly. This is absolutely not SOCI-specific.

If you still think there is something wrong with SOCI itself, please provide a concrete minimal example of what doesn't work.
