### ISSUE TITLE
Is it possible to prepare sql query without binding?

### ISSUE THREAD

**Issue by NobodyXu** [SOCI/soci#830]
Hi,

I just read the documentation regarding statement and wonders whether I can prepare sql query without binding while still get the
same speedup as preparing statement and bind a variable to it.

I came from using JDBC where binding variable is not necessary while preparing a statement and I think it is a better way, since you don't have to keep the binded variable when you are not using the query.

According to what I read [here]:

> Some backends have some facilities to improve statement parsing and compilation to limit overhead when creating commonly 
> used query. But for backends that does not support this kind optimization you can keep prepared statement and use it later 
> with new references. To do such, prepare a statement as usual, you have to use `exchange` to bind new variables 
> to statement object, then `execute` statement and finish by cleaning bound references with `bind_clean_up`.

It seems to imply that it is doable, but doing so would nullify the benefits from preparing sql statement.

[here]: http://soci.sourceforge.net/doc/release/4.0/statements/

**Comment by vadz** [comment]
I'm not sure what exactly are you asking for, but it is indeed possible to do something like this:
```
    soci::statement statement((session.prepare << query));
    ... later ...
    statement.exchange(use(param));
```

I'm not sure about the efficiency implications, but this seems a bit open-ended. If there is a real problem, please consider showing some minimal code reproducing it. Otherwise, don't hesitate to post to the mailing list to discuss this further or create PRs with the suggested improvements, but I don't think there is any real issue here, so I'm closing this one for now.
