### ISSUE TITLE
[cmake] soci doesn't export the relative path of the include directory

### ISSUE THREAD

**Issue by JackBoosY** [SOCI/soci#854]
Hi guys, 
I'm vcpkg maintainer.
Today I tried to fix soci in vcpkg (microsoft/vcpkg#16369), but I received an issue about using `soci[mysql]`:
When using `find_package(SOCI CONFIG)`, the soci header file path is not added to the generated cmake configuration file(SOCI.cmake/ SOCI-Debug.cmake/SOCI-Release.cmake). Also, the path of the soci backend mysql is not added.
I have tried to fix this issue downstream, please check the changes:
https://github.com/microsoft/vcpkg/pull/16369/files#diff-ec4e7a3492cdb5376be6a1443d0c04f742bc6bbf942371c7c46106af88d982eaR1

Thanks,
Jack

**Comment by vadz** [comment]
Sorry, I don't understand the initial problem. Who exactly is including `"soci/mysql/soci-mysql.h"`? I think it's supposed to be a private header, used only by SOCI itself.

If we want to make it public, your changes seem correct, but I'm not totally sure if we do.

**Comment by gfeyer** [comment]
Hi @vadz 
soci-mysql.h needs to be included in order to create a connection. 

See soci [documentation](http://soci.sourceforge.net/doc/master/connections/) section "Portability":
`mysql (requires #include "soci-mysql.h")
`

and is used as:
`session sql(mysql, "db=test user=root password='pwd'");
`

Thanks & Regards

**Comment by vadz** [comment]
Oops, I didn't think about this use case as I always use registered backends in my own code and so specify the backend in the connection string itself. But you're right, this should work if the docs show doing it like this.

Could you please make a PR with your changes, so that they can get tested by the CI? TIA!

**Comment by JackBoosY** [comment]
@vadz We may need to modify `soci_backend` to add private and public `target_include_directories` / `target_link_libraries`.
My modification is only a workaround.

**Comment by vadz** [comment]
Sorry, but why not modify `soci_backend` to do it then? I.e. what is the problem with doing it like this?

**Comment by JackBoosY** [comment]
@vadz Some backends depend on other libraries, some are private, and others are public.
We should only export public libraries to cmake configuration files.
So for `soci_backend`, we should distinguish between public libraries and private libraries.
