### ISSUE TITLE
failed to find shared library backend postgresql

### ISSUE THREAD

**Issue by adeolaibigbemi** [SOCI/soci#904]
Hi Everyone,
I get this error when i try to run my soci application.
failed to find shared library backend postgresql

I install via vcpkg.
libpq is installed via vcpkg too. 

Please help

**Comment by Jasonzyt** [comment]
I ran into a problem similar to yours
program failed to find shared library backend mysql&sqlite3

**Comment by vadz** [comment]
It's difficult to diagnose problems with DLL loading remotely because there are many things that could go wrong (missing DLLs; missing DLL dependencies; mismatched 32/64 DLLs; ...), but it's usually very simple to debug it locally. Just run the program under debugger and look at the debug output messages. If this is not enough, enable "loader snaps" using gflags, this should really give you all the information that you need.

**Comment by hane-junjun** [comment]
I also ran into the same problem as yours even if I use linux. (my backend is postgresql)
My application said below,
> ./test
> soci error: Failed to find shared library for backend postgresql

It seems soci shared libraries are not built when soci package is added by vcpkg.
But shared libraries are able to be built when I manually built them according to [the Instration](http://soci.sourceforge.net/doc/master/installation/)
I'd like to manage packages by vcpkg if possible so I'd like know how to build soci shared libraries when I use vcpkg.

OS: Ubuntu 20.04
```
> vcpkg/vcpkg list
abseil:x64-linux                                   20211102.1       an open-source collection designed to augment th...
c-ares:x64-linux                                   1.17.2#2         A C library for asynchronous DNS requests
grpc:x64-linux                                     1.41.0           An RPC library and framework
grpc[codegen]:x64-linux                                             Build code generator machinery
libpq:x64-linux                                    12.9#1           The official database access API of postgresql
libpq[openssl]:x64-linux                                            support for encrypted client connections and ran...
libpq[zlib]:x64-linux                                               Use zlib (else --without-zlib)
openssl:x64-linux                                  1.1.1m#2         OpenSSL is an open source project that provides ...
protobuf:x64-linux                                 3.18.0#1         Protocol Buffers - Google's data interchange format
re2:x64-linux                                      2021-11-01       RE2 is a fast, safe, thread-friendly alternative...
soci:x64-linux                                     4.0.2            SOCI database access library
soci[postgresql]:x64-linux                                          Build postgresql backend
upb:x64-linux                                      2021-10-19       μpb (often written 'upb') is a small protobuf i...
vcpkg-cmake-config:x64-linux                       2022-01-30
vcpkg-cmake:x64-linux                              2022-01-19
zlib:x64-linux                                     1.2.11#13        A compression library

> fd libsoci --no-ignore
vcpkg/installed/x64-linux/lib/libsoci_empty.a
vcpkg/installed/x64-linux/lib/libsoci_core.a
vcpkg/installed/x64-linux/lib/libsoci_postgresql.a
vcpkg/packages/soci_x64-linux/lib/libsoci_empty.a
vcpkg/packages/soci_x64-linux/lib/libsoci_core.a
vcpkg/packages/soci_x64-linux/lib/libsoci_postgresql.a
vcpkg/installed/x64-linux/debug/lib/libsoci_empty.a
vcpkg/installed/x64-linux/debug/lib/libsoci_core.a
vcpkg/installed/x64-linux/debug/lib/libsoci_postgresql.a
vcpkg/buildtrees/soci/x64-linux-rel/lib/libsoci_empty.a
vcpkg/buildtrees/soci/x64-linux-rel/lib/libsoci_core.a
vcpkg/buildtrees/soci/x64-linux-rel/lib/libsoci_postgresql.a
vcpkg/buildtrees/soci/x64-linux-dbg/lib/libsoci_empty.a
vcpkg/buildtrees/soci/x64-linux-dbg/lib/libsoci_core.a
vcpkg/buildtrees/soci/x64-linux-dbg/lib/libsoci_postgresql.a
vcpkg/packages/soci_x64-linux/debug/lib/libsoci_empty.a
vcpkg/packages/soci_x64-linux/debug/lib/libsoci_core.a
vcpkg/packages/soci_x64-linux/debug/lib/libsoci_postgresql.a
```

**Comment by vadz** [comment]
If vcpkg really doesn't build shared libraries but still builds the core library to use them, it's a bug in the package and will need to be fixed there.

I don't think there is anything wrong with SOCI itself here, so closing.

**Comment by hane-junjun** [comment]
I understand what you said. I think you are right. I shouldn't have posted the issue here.
Thank you.

**Comment by mathisloge** [comment]
Coming from the vcpkg issue: I think it's mostly a misunderstanding of vcpkg.
In the world of vcpkg, libraries are ususally build static on linux systems. This is because all libraries are build with vcpkg and there isn't such a good distribution of shared linux libraries and users often run into RPATH issues. (conflict between system and distributed libs). 

vcpkg builds the plugins in a static manner which needs other actions: https://github.com/SOCI/soci/issues/497 .
If you really want to build shared libraries on linux, you would need to use custom [triplets](https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md). 

There is a example for this https://github.com/microsoft/vcpkg/blob/7249fa4d64ead1428249895810146134be8eb881/docs/examples/overlay-triplets-linux-dynamic.md

**Comment by hane-junjun** [comment]
Thank you very much @mathisloge . I'll check the comments.

**Comment by hane-junjun** [comment]
It's me that was wrong. I didn't think I would like to have used shared libraries.
I have read the explanation, was able to find my mistake and got the problem solved: [issuecomment-1050514543](https://github.com/microsoft/vcpkg/issues/23213#issuecomment-1050514543)
Thank you very much, @mathisloge.

**Comment by Krzmbrzl** [comment]
FWIW I just ran into the (almost) same issue. However, in my case the issue was that I was establishing a connection to the DB using a connection string á la `postgresql://dbname=xyz ...`. However, I had a typo in the leading `postgresql` which caused SOCI to look for the wrong library name.
That of course was entirely a user-issue and not SOCI's fault - just wanted to document this scenario here, in case someone ends up making the same mistake as I did.

**Comment by MrStack** [comment]
I just ran into the same problem. My case is that I used static link to the libsoci_core.a but when the program runs, it searches for the dynamic lib(libsoci_postgresql.so). I solved the problem by installing the dynamic lib in the system. SOCI uses dlopen() to load the dynamic lib of specific database backend.

**Comment by mathisloge** [comment]
> I just ran into the same problem. My case is that I used static link to the libsoci_core.a but when the program runs, it searches for the dynamic lib(libsoci_postgresql.so). I solved the problem by installing the dynamic lib in the system. SOCI uses dlopen() to load the dynamic lib of specific database backend.

maybe this https://github.com/microsoft/vcpkg/issues/23213#issuecomment-1049707356 ?
